---
kind: pipeline
name: omeka:3.0.2 php:7.4 mariadb:10.6
services:
- environment:
    MYSQL_DATABASE: omeka_test
    MYSQL_ROOT_PASSWORD: root
  image: mariadb:10.6
  name: db
steps:
- commands:
  - pecl install solr
  - docker-php-ext-enable solr
  - cp -rT /usr/src/omeka-s ../..
  - git clone --depth 1 https://github.com/biblibre/omeka-s-module-Search.git ../Search
  - echo 'host = "db"\nuser = "root"\npassword = "root"\ndbname = "omeka_test"\n'
    > ../../application/test/config/database.ini
  - php ../../build/composer.phar install
  - bash -c "cd ../.. && php /usr/local/libexec/wait-for-db.php"
  - ../../vendor/bin/phpunit
  - ../../node_modules/.bin/gulp test:module:cs
  image: ghcr.io/biblibre/omeka-s-ci:3.0.2-php7.4
  name: test
  pull: always
type: docker
workspace:
  path: omeka-s/modules/Solr
---
kind: pipeline
name: omeka:3.1.2 php:7.4 mariadb:10.6
services:
- environment:
    MYSQL_DATABASE: omeka_test
    MYSQL_ROOT_PASSWORD: root
  image: mariadb:10.6
  name: db
steps:
- commands:
  - pecl install solr
  - docker-php-ext-enable solr
  - cp -rT /usr/src/omeka-s ../..
  - git clone --depth 1 https://github.com/biblibre/omeka-s-module-Search.git ../Search
  - echo 'host = "db"\nuser = "root"\npassword = "root"\ndbname = "omeka_test"\n'
    > ../../application/test/config/database.ini
  - php ../../build/composer.phar install
  - bash -c "cd ../.. && php /usr/local/libexec/wait-for-db.php"
  - ../../vendor/bin/phpunit
  - ../../node_modules/.bin/gulp test:module:cs
  image: ghcr.io/biblibre/omeka-s-ci:3.1.2-php7.4
  name: test
  pull: always
type: docker
workspace:
  path: omeka-s/modules/Solr
---
kind: pipeline
name: omeka:3.2.3 php:7.4 mariadb:10.6
services:
- environment:
    MYSQL_DATABASE: omeka_test
    MYSQL_ROOT_PASSWORD: root
  image: mariadb:10.6
  name: db
steps:
- commands:
  - pecl install solr
  - docker-php-ext-enable solr
  - cp -rT /usr/src/omeka-s ../..
  - git clone --depth 1 https://github.com/biblibre/omeka-s-module-Search.git ../Search
  - echo 'host = "db"\nuser = "root"\npassword = "root"\ndbname = "omeka_test"\n'
    > ../../application/test/config/database.ini
  - php ../../build/composer.phar install
  - bash -c "cd ../.. && php /usr/local/libexec/wait-for-db.php"
  - ../../vendor/bin/phpunit
  - ../../node_modules/.bin/gulp test:module:cs
  image: ghcr.io/biblibre/omeka-s-ci:3.2.3-php7.4
  name: test
  pull: always
type: docker
workspace:
  path: omeka-s/modules/Solr
---
kind: pipeline
name: omeka:4.0.1 php:8.0 mariadb:10.6
services:
- environment:
    MYSQL_DATABASE: omeka_test
    MYSQL_ROOT_PASSWORD: root
  image: mariadb:10.6
  name: db
steps:
- commands:
  - pecl install solr
  - docker-php-ext-enable solr
  - cp -rT /usr/src/omeka-s ../..
  - git clone --depth 1 https://github.com/biblibre/omeka-s-module-Search.git ../Search
  - echo 'host = "db"\nuser = "root"\npassword = "root"\ndbname = "omeka_test"\n'
    > ../../application/test/config/database.ini
  - php ../../build/composer.phar install
  - bash -c "cd ../.. && php /usr/local/libexec/wait-for-db.php"
  - ../../vendor/bin/phpunit
  - ../../node_modules/.bin/gulp test:module:cs
  image: ghcr.io/biblibre/omeka-s-ci:4.0.1-php8.0
  name: test
  pull: always
type: docker
workspace:
  path: omeka-s/modules/Solr
---
kind: pipeline
name: omeka:4.0.1 php:8.1 mariadb:10.6
services:
- environment:
    MYSQL_DATABASE: omeka_test
    MYSQL_ROOT_PASSWORD: root
  image: mariadb:10.6
  name: db
steps:
- commands:
  - pecl install solr
  - docker-php-ext-enable solr
  - cp -rT /usr/src/omeka-s ../..
  - git clone --depth 1 https://github.com/biblibre/omeka-s-module-Search.git ../Search
  - echo 'host = "db"\nuser = "root"\npassword = "root"\ndbname = "omeka_test"\n'
    > ../../application/test/config/database.ini
  - php ../../build/composer.phar install
  - bash -c "cd ../.. && php /usr/local/libexec/wait-for-db.php"
  - ../../vendor/bin/phpunit
  - ../../node_modules/.bin/gulp test:module:cs
  image: ghcr.io/biblibre/omeka-s-ci:4.0.1-php8.1
  name: test
  pull: always
type: docker
workspace:
  path: omeka-s/modules/Solr
---
kind: pipeline
name: omeka:4.0.1 php:8.2 mariadb:10.6
services:
- environment:
    MYSQL_DATABASE: omeka_test
    MYSQL_ROOT_PASSWORD: root
  image: mariadb:10.6
  name: db
steps:
- commands:
  - pecl install solr
  - docker-php-ext-enable solr
  - cp -rT /usr/src/omeka-s ../..
  - git clone --depth 1 https://github.com/biblibre/omeka-s-module-Search.git ../Search
  - echo 'host = "db"\nuser = "root"\npassword = "root"\ndbname = "omeka_test"\n'
    > ../../application/test/config/database.ini
  - php ../../build/composer.phar install
  - bash -c "cd ../.. && php /usr/local/libexec/wait-for-db.php"
  - ../../vendor/bin/phpunit
  - ../../node_modules/.bin/gulp test:module:cs
  image: ghcr.io/biblibre/omeka-s-ci:4.0.1-php8.2
  name: test
  pull: always
type: docker
workspace:
  path: omeka-s/modules/Solr
---
kind: signature
hmac: 75379dce3ad3ada828ac44cd7b8f9a9add6362bf8caa3bbf4a2a5b4e55e78d25

...
