<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/transformations-form.css', 'Solr'));
$this->headScript()->appendFile($this->assetUrl('vendor/sortablejs/Sortable.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/transformations-form.js', 'Solr'));

$solr_mapping_id = $element->getOption('solr_mapping_id');
?>
<div class="transformations-form-element"
    data-transformation-list-url="<?= $this->url('admin/solr/transformations', ['action' => 'transformation-list'], ['query' => ['solr_mapping_id' => $solr_mapping_id]]) ?>"
    data-transformation-row-url="<?php echo $this->escapeHtml($this->url('admin/solr/transformations', ['action' => 'transformation-row'])); ?>"
    data-transformation-edit-sidebar-url="<?php echo $this->escapeHtml($this->url('admin/solr/transformations', ['action' => 'transformation-edit-sidebar'])); ?>">
    <?php $element->setValue(''); ?>
    <?php echo $this->formHidden($element); ?>
    <fieldset class="transformation-add-group">
        <?php
        $select = new \Laminas\Form\Element\Select('transformation_name_select');
        $select->setAttribute('class', 'transformations-transformation-name-select');
        $select->setEmptyOption($element->getOption('empty_option'));
        $select->setValueOptions($element->getOption('value_options'));
        ?>
        <?= $this->formSelect($select); ?>
        <button type="button" class="transformations-transformation-add-button o-icon-add" disabled aria-label="<?php echo $this->translate('Add'); ?>" title="<?php echo $this->translate('Add'); ?>"></button>
    </fieldset>
    <ul class="transformations-transformations"></ul>
</div>
